### PR TITLE
Update swagger UI to version 3.x

### PR DESCRIPTION
**Pull request by moserke**
This updates the UI to use the new react based Swagger UI.  This UI was rewritten from the ground up and has a lot of new features.  It keeps rswag in line with the swagger ui project as well.

This is another take or leave it PR....

### CODE REVIEW

**Comment by moserke** [comment]
Resolves #62

**Comment by ingemar** [comment]
Bump!

**Comment by san983** [comment]
Why hasn't this been considered for merging?

**Comment by domaindrivendev** [comment]
Closing in favor of #121. The main difference being that 121 converts the UI implementation to middleware. This means it should work out-of-the-box for api-only Rails apps.

**Pull request closed without merging**
