### PR TITLE
add formData support

### PR DESCRIPTION
**Pull request by thg303**
related to issue #53

### CODE REVIEW

**Comment by pifleo** [comment]
Hey @thg303,

I had a look at your PR, and tested your code in place of [my patch](https://github.com/domaindrivendev/rswag/issues/53#issuecomment-294158739) in my code. 
It’s not working with a parameter of this form: `parameter name: :file, in: :formData, type: :file, required: true`.

From the Swagger spec it is also possible to have multiple `formData` parameters but only one` body` parameter is allowed, and your code in  ` request_factory.rb` doesn’t allow that as you use `first` on the param.
You put many parameter with formData in your spec but only the first ` 'blog[title]'
` is send with the request.

Your spec is interesting because the name of your params is a string with a scope, you should keep one like that.
You should keep a spec validating a parameter with the type `body`

Thanks for working on it

**Comment by thg303** [comment]
thank you @pifleo , I refactored my PR to fix those issues

**Comment by domaindrivendev** [comment]
@thg303 - thanks for this contribution. I'm still taking some time to go through it. One area that doesn't feel quite right, and may just be a limitation with Rails integration tests, is the way in which the client (i.e. the example) sends a Ruby hash for these form parameters. I would prefer it to simulate a "real" API client and send the body as a url-form-encoded string - similar to how the JSON body parameters are being submitted.

**Comment by thg303** [comment]
@domaindrivendev I see what you mean, but unfortunately I could not come up with a real request simulation approach, as you mentioned seems to be a rails issue. by the way since the request is about to go to the rails, and it comes from rails, that would be an inner issue and could be ignored without any side effect.

**Comment by citrusoft** [comment]
this is a very useful PR.  its been over two months.  why has this gone cold?  when are you planning to merge?

**Comment by citrusoft** [comment]
Conlater.grats on the pull request acceptance.  Will be using this sooner
or

Tommy Hunt, CEA, PMP, PSM, SAFe Program Consultant
http://www.citrusoft.com
citrusoft@gmail.com
425-298-6551
Sent with Samsung Tab 3.

**Pull request merged**
