### PR TITLE
Using Servers block first url during request building for OAS3 compatible documents

### PR DESCRIPTION
**Pull request by developingchris**
This PR adds support for using the servers block during test time to keep from having a v2 test configuration and v3 publish difference.

### CODE REVIEW

**Comment by developingchris** [comment]
@oblakeerickson  I'm looking for some initial feedback on this approach? Does this make sense?

**Comment by kwstannard** [comment]
This is an interesting approach. My suggestion would be to set base_path as possibly a Rswag::Specs.config method that defaults to your implementation if not specified.

**Comment by developingchris** [comment]
> This is an interesting approach. My suggestion would be to set base_path as possibly a Rswag::Specs.config method that defaults to your implementation if not specified.

In trying to get our swagger file to validate using several OAS 3 checkers, we received errors when specifying OAS 3 and including the base_path. So while ergonomically that feels good for users of Rswag, it is generating a file which generates errors elsewhere.

**Comment by kwstannard** [comment]
The base_path would be in the config, not in the swagger doc.

**Pull request closed without merging**
