### PR TITLE
upgrade to ruby 3.0.6 and rails 7.0.4.3 in local dev

### LINKED ISSUE #624: [REQUEST] Develop for Ruby version 3.0.x
## Is your feature request related to a problem? Please describe.

Currently, rswag develops against ruby 2.7.6, which is EOL.

https://endoflife.date/ruby

https://github.com/rswag/rswag/blob/master/.ruby-version

https://github.com/rswag/rswag/blob/master/Dockerfile

## Describe the solution you'd like

Upgrading both to at minimum ruby 3.0.x should do :) 

## What support could we give you, so you could implement this yourself?

https://github.com/rswag/rswag/pull/625

## Describe alternatives you've considered

I haven't considered any alternatives.

## Relates to which version of OAS (OpenAPI Specification)
- [ ] OAS2
- [ ] OAS3
- [ ] OAS3.1

### PR DESCRIPTION
**Pull request by Zarthus**
## Problem
Please refer to issue #624 for insights

### Related Issues

https://github.com/rswag/rswag/issues/624

### Checklist
- [ ] Added tests
- [ ] Changelog updated
- [ ] Added documentation to README.md

### Steps to Test or Reproduce
Outline the steps to test or reproduce the PR here.

### CODE REVIEW

**Review by romanblanco — CHANGES_REQUESTED** [review]
Thank you, for the PR, @Zarthus!

[`.github/workflows/ruby.yml`](https://github.com/rswag/rswag/blob/master/.github/workflows/ruby.yml) needs to be updated as well

**Comment by Zarthus** [comment]
@romanblanco 

Hi, I pushed two new commits to handle your feedback.

**Review by romanblanco — CHANGES_REQUESTED** [review]
These warnings should be removed:

https://github.com/Zarthus/rswag/blob/f5d0674398f40dea995b1fb72049e1d35757b4b9/rswag-specs/lib/rswag/specs/example_group_helpers.rb#L8

https://github.com/Zarthus/rswag/blob/f5d0674398f40dea995b1fb72049e1d35757b4b9/rswag-specs/lib/rswag/specs/swagger_formatter.rb#L10

This case too:

https://github.com/Zarthus/rswag/blob/f5d0674398f40dea995b1fb72049e1d35757b4b9/Gemfile#L20

**Comment by romanblanco** [comment]
@Zarthus, please, search through the repository and see if there are any remnants for the Ruby version to remove.

FYI, the `swagger_formatter.rb` will be renamed once https://github.com/rswag/rswag/pull/574#issuecomment-1532497164 is merged.

**Comment by Zarthus** [comment]
@romanblanco could you approve this MR to run the workflows so I can see if any tests fail too?

I will get back on this next week as I'm unavailable for the rest of this week, if you're eager to merge this sooner feel free to commit on top of my branch or cherry-pick the commits.

**Comment by Zarthus** [comment]
Sorry it took a while, [this commit](https://github.com/rswag/rswag/pull/625/commits/1d200789a55460b881f07f6e78067e0dff771162) handles your feedback.

**Comment by brcebn** [comment]
I think changes have been made @romanblanco isn't it?

**Review by romanblanco — APPROVED** [review]
@benebrice, @Zarthus 

Thank you for addressing the feedback!

@Zarthus, I've changed target for the branch to https://github.com/rswag/rswag/tree/v3, in which we're preparing changes for rswag v3.

Because of that, your branch now has conflicts (e.g. `swagger_formatter.rb` has been renamed to `openapi_formatter.rb`).

The PR is also missing an update of `CHANGELOG.md`, but once the conflict is resolved, I'm ready to merge this PR.

**Comment by Zarthus** [comment]
Hi @romanblanco, is the question if I'd be willing to perform the conflict resolution, or is that something you'll handle? - I allow commits to be added by maintainers.

**Comment by romanblanco** [comment]
@Zarthus Thank you for the quick response! I've added some more changes and merged it into `v3`.

**Comment by Zarthus** [comment]
@romanblanco Thanks for getting this over the finish line! Appreciate it :)

**Pull request merged**
