### PR TITLE
Support arel like query parameters

### PR DESCRIPTION
**Pull request by horiaradu**
* especially useful when combining with ransack

### CODE REVIEW

**Comment by horiaradu** [comment]
@domaindrivendev could you take a look at this when you have time? Thanks!

**Comment by domaindrivendev** [comment]
Hey there. Thanks for the contribution but my position at this point is to only support the `collectionFormat` values that are defined in the [Swagger specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).

**Comment by horiaradu** [comment]
What do you think about maybe using a different type, not ‘collectionFormat’. I think arel is a very useful type to supoort. I could adapt / change the code if you have an idea about what type we could use...

**Comment by domaindrivendev** [comment]
Swagger is a technology agnostic specification for describing HTTP/REST based API's. Therefore, there should be nothing in the description that refers to Rails specific concepts. With that in mind, you're really just referring to a set of query parameters with a very specific naming format, which can be set up as follows:

```ruby
get 'Test' do
  tags 'Blogs'
  description 'test'
  operationId 'test'
  produces 'application/json'
  parameter name: :'test[foo]', :in => :query, :type => :string
  parameter name: :'test[bar]', :in => :query, :type => :string

  response '200', 'test' do
    let(:'test[foo]') { 'val1' }
    let(:'test[bar]') { 'val2' }
    run_test!
  end
end
```

**Comment by horiaradu** [comment]
Ok, cool. Thanks a lot for the suggestion, I will use it.

Thanks for your time!

**Pull request closed without merging**
