### PR TITLE
docs: add IRC channel for #rswag into README

### PR DESCRIPTION
**Pull request by romanblanco**
## Solution
Proposing IRC as a way to communicate more efficiently.

### Related Issues
https://github.com/rswag/rswag/discussions/495#discussioncomment-4080562

### Checklist
- ~Added tests~
- [ ] Changelog updated
- [ ] Added documentation to README.md

### CODE REVIEW

**Comment by mattpolito** [comment]
I'm open to give it a try but I wouldn't call IRC 'more efficient'.

**Comment by mattpolito** [comment]
Unless I'm completely missing something... history is lost when I leave IRC. So I can't see how this would be a viable option to communicate for an open-source project. There needs to be a history for someone to catch up on. 

Please let me know if I'm missing something.

**Comment by romanblanco** [comment]
@mattpolito, to get the history, one of the options is to use another platform (e.g. [Matrix](matrix.org)) that has a bridge to IRC.

I would've proposed using Matrix directly in the first place, but thought that using IRC is more inclusive and easier as one does not need to register an account to join the chat.

**Comment by mattpolito** [comment]
@romanblanco Thanks for that info. I would say that if you need to use a specific client or platform to get history, then IRC would not be a helpful option. What were the motivating factors to moving toward a chat client?

**Comment by romanblanco** [comment]
@mattpolito see https://github.com/rswag/rswag/discussions/495#discussioncomment-3609613

**Pull request closed without merging**
