### PR TITLE
Limit comments to 80 characters width

### PR DESCRIPTION
**Pull request by mkllnk**
And adding some punctuation for easier reading. This should comply with common style guides.

### CODE REVIEW

**Review by jtannas — COMMENTED** [review]
lgtm but I'm hesitant about making style changes until we put in a Rubocop styleguide (on our near future ToDo list) so we can be consistent. Think you'd be willing to put that together or would you prefer to wait?

**Review by jtannas — APPROVED** [review]

**Comment by jtannas** [comment]
@BookOfGreg just changes to the comment linebreaks.
Seems good to get this out of the review queue and deal with the larger question of rubocop later.

**Comment by jtannas** [comment]
@mkllnk I've got merge-powers on this repo now. If you get the merge conflicts resolved I'll get this in.

**Comment by mkllnk** [comment]
Thank you. I resolved the merge conflict.

**Review by jtannas — APPROVED** [review]

**Pull request merged**
