### PR TITLE
OpenAPI 3.0 Response Examples

### PR DESCRIPTION
**Pull request by mia-n**
Just stumbled upon #302 and #305 after doing this work, so most likely this will be disregarded, but I figure it can't hurt to share in case part of this is useful.

The part of this that feels particularly important to me that #302 and #305 are not doing (at the time that I write this PR description) is prevent overwriting any existing response content. This is important to continue to support automatic response example creation. The current README still includes a note about enabling automatic example generation from responses by adding:

```
after do |example|
  example.metadata[:response][:examples] = { 'application/json' => JSON.parse(response.body, symbolize_names: true) }
end
```

This can be replaced with something like:
```
after do |example|
  example.metadata[:response][:content] = {
    "application/json" => {
        examples: {
            autogenerated_example: {
                value: JSON.parse(response.body, symbolize_names: true)
            }
        }
    }
  }
end
```

However, current code (and the changes added in #302 and #305 at the time of this writing) have a call to `target_node.merge!(content: {})` in swagger_formatter.rb that completely wipes out any automatically generated responses added in this way.

My proposed changes use a soft check to the existence of the content hash before appending it to allow any pre-existing content to be retained.

```
if target_node[:content].nil?
          target_node.merge!(content: {})
end
```

I'm happy to close this and abandon my changes if the changes in #302 or #305 are considered better additions, but it's important to me that somehow the ability to append automatic response examples is retained.

### CODE REVIEW

**Comment by chewi** [comment]
My work in #305 does allow automatic response examples. I can update the README with the new snippet as you have done tomorrow.

**Comment by mia-n** [comment]
> My work in #305 does allow automatic response examples. I can update the README with the new snippet as you have done tomorrow.

Oh awesome! I must've missed that. I'll close this.

**Comment by mia-n** [comment]
> My work in #305 does allow automatic response examples. I can update the README with the new snippet as you have done tomorrow.

Wait, @chewi  I'm looking through #305 again - won't the remaining call to 
`target_node.merge!(content: {})`
in your code wipe out those kind of automatic examples? I feel like I'm missing something.

**Comment by chewi** [comment]
My code picks them up from `example.metadata[:response][:examples]` rather than `example.metadata[:response][:content][mime][:examples]` in the same way that the schema is already handled. Under OpenAPI V3, `schema` is also under `content`. This compatibility stuff with V2 is weird but I'm just keeping it consistent.

**Comment by mia-n** [comment]
Cool makes sense :)

**Comment by chewi** [comment]
If you didn't notice yet, I did update the README, which should show how to use mine. Let me know if you have any trouble.

**Comment by mia-n** [comment]
> If you didn't notice yet, I did update the README, which should show how to use mine. Let me know if you have any trouble.

Thanks! I'll close this now. Hopefully yours gets merged soon.

**Comment by jmajonis** [comment]
@chewi Do you have advice how to try your feature branch in a local Rails project?

I've tried bundling the following from the Gemfile: 

```
gem 'rswag', git: 'https://github.com/chewi/rswag.git', branch: 'response-examples'
```
and 

```
git 'https://github.com/chewi/rswag.git', branch: 'response-examples' do
  gem 'rswag-api'
  gem 'rswag-specs'
  gem 'rswag-ui'
end
```

But after building a new Docker image and restarting I get errors related to `swagger-ui`

```
Started GET "/api-docs/index.html" for 192.168.112.1 at 2020-05-12 17:19:39 +0000
ActionController::RoutingError (No route matches [GET] "/api-docs/swagger-ui.css"):
ActionController::RoutingError (No route matches [GET] "/api-docs/swagger-ui-standalone-preset.js"):
ActionController::RoutingError (No route matches [GET] "/api-docs/swagger-ui-bundle.js"):
ActionController::RoutingError (No route matches [GET] "/api-docs/swagger-ui-bundle.js"):
ActionController::RoutingError (No route matches [GET] "/api-docs/swagger-ui-standalone-preset.js"):
```

I'm sure it's not your feature branch. I'm misunderstanding something about how to bundle from a Git source.

**Pull request closed without merging**
