### PR TITLE
🔒Add Optional Basic Auth for Rswag UI

### PR DESCRIPTION
**Pull request by akabiru**
## Description

Hey @domaindrivendev , thanks for the awesome work on `Rswag`. It's literally saving lives! 🙂

I thought I'd drop in a feature to allow folks who'd rather have their docs protected/private, at the moment it's via Basic Auth.

### CODE REVIEW

**Comment by moeenzarrinfam** [comment]
I need this feature.
@BookOfGreg when you can accept the pull request?

**Comment by akabiru** [comment]
> I need this feature.
> @BookOfGreg when you can accept the pull request?

Hey @moeenzarrinfam 👋 . In case this is useful, you can plug this into your `application.rb` (if on Rails) to get early access!

```ruby
# config/application.rb

class DocsBasicAuth < ::Rack::Auth::Basic
  DOCS_PATH = '/api-docs'.freeze

  def call(env)
    return @app.call(env) unless env['PATH_INFO'].match?(%r{/api-docs/?})

    super(env)
  end
end

# FIXME: Remove & update rswag-ui once (if)
# https://github.com/rswag/rswag/pull/167 is merged
Rswag::Ui::Engine.class_eval do
  initializer 'rswag-ui.initialize' do |app|
    app.middleware.use DocsBasicAuth do |username_input, password_input|
      username = ENV['DOCS_USER'] || 'yourusersname'
      password = ENV['DOCS_PASSWORD'] || 'yourpassword'

      # Protect against timing attacks - use constant time comparison
      ActiveSupport::SecurityUtils.secure_compare(
        ::Digest::SHA256.hexdigest(username_input),
        ::Digest::SHA256.hexdigest(username)
      ) & ActiveSupport::SecurityUtils.secure_compare(
        ::Digest::SHA256.hexdigest(password_input),
        ::Digest::SHA256.hexdigest(password)
      )
    end
  end
end
```

**Comment by iamchrismiller** [comment]
Where does this PR stand? This seems like a great feature for our org as well.

**Review by akabiru — COMMENTED** [review]
Submitting this for initial review: 👁 

One key future improvement IMO would be to add integration tests for this feature that utilises the `TestApp` rails application.

**Comment by jspooner** [comment]
We could use this feature as well.  We can't install this branch because of the [npm build dependency ](https://github.com/rswag/rswag/blob/master/ci/build.sh).  Has anyone published this fork to ruby gems or can get this merged into master?

**Comment by akabiru** [comment]
> We could use this feature as well. We can't install this branch because of the [npm build dependency ](https://github.com/rswag/rswag/blob/master/ci/build.sh). Has anyone published this fork to ruby gems or can get this merged into master?

@jspooner Have a look at https://github.com/rswag/rswag/pull/167#issuecomment-571027396 as workaround before this is merged. 🙂

**Comment by akabiru** [comment]
Hi @BookOfGreg , gentle reminder about this one when you have a moment. 👍

**Comment by rromanchuk** [comment]
this this a polite plea to project owner, if still time constrained, please think about assigning contributors with meaningful write access. This at least signals to the rest of the community that it's not a waste of their time to submit quality contributions. Even if it's just to cleanup administratively. This was submitted in 2018, we're now in the great pandemic of 2020 and specification `2.0` has come and gone, and i'm just trying to write some great documentation. Please merge.

**Pull request merged**
