### PR TITLE
Add a license

### PR DESCRIPTION
**Pull request by chrisf**
rswag doesn't currently specify a license, so it would be nice to have one

https://choosealicense.com/licenses/mit/

### CODE REVIEW

**Comment by flyfy1** [comment]
Hi @chrisf, the license is in each of the sub-folder for this library

**Comment by chrisf** [comment]
Don’t know how I missed that! If that’s the case, maybe we can add a mention in the README in the root folder so it’s easier to discover. 

Since it looks like they’re all the same license, would it be possible to add one to the root folder as well so GitHub detects it?

**Comment by flyfy1** [comment]
haha I think it's a good idea but I'm not the repo's owner..

**Comment by BookOfGreg** [comment]
I got you fam 👍

**Pull request closed without merging**
