### PR TITLE
Upgrade json-schema

### LINKED ISSUE #666: [REQUEST] Improve strict schema validation
## Is your feature request related to a problem? Please describe.
https://github.com/rswag/rswag/pull/604#issuecomment-1641941197

## Describe the solution you'd like
Use `allPropertiesRequired` and `noAdditionalProperties` options for json-schema gem implemented in https://github.com/voxpupuli/json-schema/pull/494.

## Relates to which version of OAS (OpenAPI Specification)
- OAS3
- OAS3.1

### LINKED ISSUE #669: [REQUEST] upgrade `json-schema` support to 4.0
## Is your feature request related to a problem? Please describe.
Currently `json-schema` is restricted in the gemspec to be `>= 2.2, < 4.0`. 

## Describe the solution you'd like
change limit on `json-schema` be either `>= 2.2, < 5.0` or. `>= 2.2`

## What support could we give you, so you could implement this yourself?
breaking for 4.0 is:
- Removed `data` ivar from JSON::Validator so that multiple validate call become faster

I can't seem to find the usage of said ivar. Where would I need to look?

## Describe alternatives you've considered
stick with the older version?

## Additional context
we use schema validations for our API so keeping up to date with the latest version would be desirable as additionally there seems no support for older versions

### PR DESCRIPTION
**Pull request by IlkhamGaysin**
## Problem
To extend the rswag with changes on the strictnesses of schemas we need to use the new version of https://github.com/voxpupuli/json-schema/pull/494

## Solution
Upgrade the `json-schema` gem as the first step. It seems there are no breaking changes affecting rswag. https://github.com/voxpupuli/json-schema/commit/f5071e13ab037882dbb3725eb7915e1868a57f86

### This concerns this parts of the OpenAPI Specification:
* [EXAMPLE_LINK TO RELEVANT OPEN API SPECS PAGE](https://spec.openapis.org/oas/v3.1.0#data-types)
* [ANOTHER LINK TO RELEVANT OPEN API SPECS PAGE](https://spec.openapis.org/oas/v3.1.0#schema)

### The changes I made are compatible with:
- [ ] OAS2
- [ ] OAS3
- [ ] OAS3.1

### Related Issues
https://github.com/rswag/rswag/pull/604#issuecomment-1641941197
https://github.com/rswag/rswag/issues/666

### Checklist
- [ ] Added tests
- [ ] Changelog updated
- [ ] Added documentation to README.md
- [ ] Added example of using the enhancement into [test-app](https://github.com/rswag/rswag/tree/master/test-app)

### Steps to Test or Reproduce
Outline the steps to test or reproduce the PR here.

### CODE REVIEW

**Comment by IlkhamGaysin** [comment]
@romanblanco could you please check this? Thanks!

**Comment by a-lavis** [comment]
https://github.com/voxpupuli/json-schema/pull/494

is unreleased.  So upgrading to `json-schema` 4.0 will not give us access to that feature.

**Comment by IlkhamGaysin** [comment]
@a-lavis yeah, see... I've checked the fork thinking it's released :D
Thanks!
let's wait...

**Comment by romanblanco** [comment]
@IlkhamGaysin, I see that @a-lavis's changes were released in 4.1.0: https://github.com/voxpupuli/json-schema/compare/v4.0.0...v4.1.1.

**Comment by germs12** [comment]
+1 on getting this merged!

**Comment by romanblanco** [comment]
Closing this as a duplicate of https://github.com/rswag/rswag/pull/659

**Pull request closed without merging**
