### PR TITLE
Ability to use apiKey pairs in requests

### PR DESCRIPTION
**Pull request by daniel-sullivan**
As per #88

### CODE REVIEW

**Comment by daniel-sullivan** [comment]
Apologies for the double post - accidentally did the pull from master rather than branching and ended up making a mess.

**Comment by karloscodes** [comment]
Any update on this?

**Comment by dkniffin** [comment]
I know this is really old at this point, but is there any update? @daniel-sullivan or @domaindrivendev has this been merged in another PR at this point? Or should someone champion getting this merged?

What I'm looking for is the ability to define an endpoint that requires multiple authentication headers.

**Comment by dkniffin** [comment]
@domaindrivendev Bump again. It looks like this repo is starting to go abandoned a bit. Do you want any help triaging issues and pull requests?

**Comment by sergioisidoro** [comment]
@dkniffin According to https://github.com/rswag/rswag/issues/88#issuecomment-326619145 this issue was fixed in v1.5.2 but there's an open issue about this on https://github.com/swagger-api/swagger-core/issues/3024

Can you confirm that this is still valid?

**Comment by dkniffin** [comment]
@sergioisidoro I'm no longer working with rswag at all, so I cannot confirm whether this is still an issue or not

**Comment by sergioisidoro** [comment]
This is quite stale, and given that the author is no longer using Rswag, I think we can close. 

Thanks @dkniffin for giving a shot at this :) And sorry this ended up in the drawer, but right now we need to be a bit aggressive with closing stale work to bring the project up to speed.

**Pull request closed without merging**
