### PR TITLE
Fix Authorization header missing and duplicating

### LINKED ISSUE #111: No Authorization header added if there are no other params
In my swagger_helper.rb I have this:

```
securityDefinitions: {
  api_key: {
    type: :apiKey,
    name: 'Authorization',
    in: :header
  }
}
```

Spec:
```
require 'swagger_helper'

RSpec.describe EntitiesController do
  let(:Authorization) { 'Bearer some_token' }

  path '/entities' do
    get 'Fetch all entities' do
      security [api_key: {}]

      response '200', 'Entities list' do
        schema type: 'array',
               items: { '$ref' => '#/definitions/entity' }

        run_test!
      end
    end
  end
end
```

That spec produces this in resulting swagger.json:
```
"/entities": {
  "get": {
    "summary": "Fetch all entities",
    "security": [
      {
        "api_key": {
        }
      }
    ],
    "responses": {
      "200": {
        "description": "Entities list",
        "schema": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/entity"
          }
        }
      }
    }
  }
}
```

As you can see there is no `parameters` section in that json file at all and also there is no Authorization header there despite the `security` helper has been called explicitly.

If I add some parameter in spec like this:
```
require 'swagger_helper'

RSpec.describe EntitiesController do
  let(:Authorization) { 'Bearer some_token' }

  path '/entities' do
    get 'Fetch all entities' do
      security [api_key: {}]
      parameter name: :some_param, in: :path, type: :integer

      response '200', 'Entities list' do
        schema type: 'array',
               items: { '$ref' => '#/definitions/entity' }

        let(:some_param) { 1 }

        run_test!
      end
    end
  end
end
```

Then everything looks good:
```
"/entities": {
  "get": {
    "summary": "Fetch all entities",
    "security": [
      {
        "api_key": {
        }
      }
    ],
    "parameters": [
      {
        "name": "some_param",
        "in": "path",
        "type": "integer",
        "required": true
      },
      {
        "name": "Authorization",
        "in": "header",
        "type": "string",
        "required": true
      }
    ],
    "responses": {
      "200": {
        "description": "Entities list",
        "schema": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/entity"
          }
        }
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by akurashev**
It fixes #111 and #110

### CODE REVIEW

**Review by ozbendavid — APPROVED** [review]

**Comment by gpalozzi** [comment]
@akurashev Do you think this fix is going to be merged soon?

**Comment by akurashev** [comment]
@gpalozzi Unfortunately I have no idea. I've got no feedback on this PR or respective issue.

**Comment by gpalozzi** [comment]
@akurashev I'm going to use your version until after @domaindrivendev merge the fix. Thanks for your time!

**Comment by domaindrivendev** [comment]
Will try take a look at this today

**Comment by vasiliqa** [comment]
Maybe correct behaviour should be: "Add a token in the request header automatically after authorisation form submit and don't add separate authorisation parameter to every example?". Especially since this parameter value is not taken into account, and value from the form is sent in request headers.

**Pull request merged**
