### PR TITLE
Configurable Host header

### PR DESCRIPTION
**Pull request by amiuhle**
Reads the `host` property and sets the `Host` request header accordingly.

### CODE REVIEW

**Comment by fabn** [comment]
This is very useful, why don't accepting it?

**Comment by BookOfGreg** [comment]
1. I just started maintaining this gem within the last couple weekends. It takes time.
2. The PR itself changes way more than the title says.

**Comment by amiuhle** [comment]
@BookOfGreg I needed to rebase this on the rails 6 branch, the actual change is just this commit: https://github.com/rswag/rswag/pull/184/commits/c2f84ff354ba8ede50af106b61db124a7148af22

**Comment by amiuhle** [comment]
I rebased on `master`, should be easy to merge now.

Thanks for maintaining this gem!

**Comment by bstie** [comment]
Is there a chance that this PR will be accepted?

**Comment by sergioisidoro** [comment]
@amiuhle would it be possible to add a test for this (or at least add it to the test app examples)?
I think if there's a test we can move this forward.

**Review by jtannas — COMMENTED** [review]
@amiuhle sorry for the long wait. I've only recently begun working as a maintainer on this project and am trying to catch up on everything.

This looks like a simple & useful addition, and I'd be happy to merge it in once there's tests added and an accompanying Changelog entry :)
Thanks!

**Comment by romanblanco** [comment]
@amiuhle @jtannas I've cherry-picked commit from this PR and added tests in https://github.com/rswag/rswag/pull/570 to help this get merged soon.

**Pull request closed without merging**
