### PR TITLE
Fix routes method in RoutePareser

### PR DESCRIPTION
**Pull request by graceful-potato**
Fix for #323

### CODE REVIEW

**Comment by flyfy1** [comment]
Thx, I applied your fix locally and it helps resolving exactly the same issue that I'm facing.

Interestingly we could encounter such kind of issue here..

**Comment by graceful-potato** [comment]
According to the git blame they changed `reduce` to `each_with_object` because of rubocop, and forgot that the block's signature is different for these methods.
But the fact that this bug has been here for two months is a bit weird.

**Comment by VoltanBro** [comment]
Thx u bro!

**Comment by flyfy1** [comment]
Hi @BookOfGreg could u take a look into this one?

**Comment by deniciocode** [comment]
Hey,
I also applied these changes locally and I am able to use the generator now.

**Comment by andrepcg** [comment]
Thanks, it fixes it!

**Comment by graceful-potato** [comment]
@BookOfGreg

**Comment by ronail** [comment]
works like a charm! When can we have this merged?

**Review by maycowmeira — APPROVED** [review]

**Comment by dhivyada** [comment]
Please merge this to the base repo soon and release

**Comment by drselump14** [comment]
When this bug fixed will be released?

**Comment by BookOfGreg** [comment]
> 
> 
> According to the git blame they changed `reduce` to `each_with_object` because of rubocop, and forgot that the block's signature is different for these methods.
> But the fact that this bug has been here for two months is a bit weird.

Yeah that's really embarrassing. Sorry everyone!

**Comment by LE-HU** [comment]
Guys I have an impression this problem persists in current 2.3.1 release. I've just started a new project and had to do the fix locally in order for generator to work.

Okay i just realized 2.3.1 was released in April and the fix is from May, shouldn't this fix be published so it's fixed automatically? Idk if what i'm saying makes sense as I'm pretty new around here, but as far as I understand everyone installing rswag currently have to do the fix manually.

**Comment by jimbali** [comment]
@LE-HU Agreed. @BookOfGreg how do we go about getting this released please?

**Comment by kamalpanhwar** [comment]
This issue still in latest version not seem not merged yet.

**Pull request merged**
