### PR TITLE
bump swagger-ui-dist to 5.9.0

### PR DESCRIPTION
**Pull request by gobijan**
## Problem
Swagger UI was 4.1.3. The newest version is 5.9.0. This is just a dependency bump. Tests were locally fine except pending examples. "Pending: (Failures listed here are expected and do not affect your suite's status)" I guess PR should be fine then.

####################
Unit Tests
####################
```
##### rswag-api #####
..............

Finished in 0.00952 seconds (files took 1.53 seconds to load)
14 examples, 0 failures

Coverage report generated for RSpec to /Users/bijan/dev/ruby/rswag/rswag-api/coverage. 51 / 51 LOC (100.0%) covered.
##### rswag-specs #####
..................................WARNING: Using `expect { }.not_to raise_error(SpecificErrorClass)` risks false positives, since literally any other error would cause the expectation to pass, including those raised by Ruby (e.g. `NoMethodError`, `NameError` and `ArgumentError`), meaning the code you are intending to test may not even get reached. Instead consider using `expect { }.not_to raise_error` or `expect { }.to raise_error(DifferentSpecificErrorClass)`. This message can be suppressed by setting: `RSpec::Expectations.configuration.on_potential_false_positives = :nothing`. Called from /Users/bijan/dev/ruby/rswag/rswag-specs/spec/rswag/specs/request_factory_spec.rb:44:in `block (5 levels) in <module:Specs>'.
WARNING: Using `expect { }.not_to raise_error(SpecificErrorClass)` risks false positives, since literally any other error would cause the expectation to pass, including those raised by Ruby (e.g. `NoMethodError`, `NameError` and `ArgumentError`), meaning the code you are intending to test may not even get reached. Instead consider using `expect { }.not_to raise_error` or `expect { }.to raise_error(DifferentSpecificErrorClass)`. This message can be suppressed by setting: `RSpec::Expectations.configuration.on_potential_false_positives = :nothing`. Called from /Users/bijan/dev/ruby/rswag/rswag-specs/spec/rswag/specs/request_factory_spec.rb:45:in `block (5 levels) in <module:Specs>'.
......................................................................................

Finished in 0.06021 seconds (files took 0.34182 seconds to load)
120 examples, 0 failures

Coverage report generated for RSpec to /Users/bijan/dev/ruby/rswag/rswag-specs/coverage. 519 / 545 LOC (95.23%) covered.
##### rswag-ui #####
......

Finished in 0.01082 seconds (files took 0.26819 seconds to load)
6 examples, 0 failures

Coverage report generated for RSpec to /Users/bijan/dev/ruby/rswag/rswag-ui/coverage. 36 / 39 LOC (92.31%) covered.
####################
Integration Tests
####################

##### test-app #####
== 20160218212104 CreateBlogs: migrating ======================================
-- create_table(:blogs, {:id=>:integer})
   -> 0.0010s
== 20160218212104 CreateBlogs: migrated (0.0010s) =============================

*.......................*......*DEPRECATION WARNING: Rswag::Specs: WARNING: Support for RSpec 2.X will be dropped in v3.0 (called from block (2 levels) in <top (required)> at /Users/bijan/dev/ruby/rswag/test-app/spec/rake/rswag_specs_swaggerize_spec.rb:14)
/Users/bijan/.rbenv/versions/2.7.6/bin/ruby -I/Users/bijan/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.2/lib:/Users/bijan/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rspec-support-3.12.1/lib /Users/bijan/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.2/exe/rspec --pattern spec/requests/\*\*/\*_spec.rb,\ spec/api/\*\*/\*_spec.rb,\ spec/integration/\*\*/\*_spec.rb --format Rswag::Specs::SwaggerFormatter --order defined
Generating Swagger docs ...
Swagger doc generated at /Users/bijan/dev/ruby/rswag/test-app/swagger/v1/swagger.json
Swagger doc generated at /Users/bijan/dev/ruby/rswag/test-app/swagger/v3/openapi.json

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) Generated OpenApi Media Types /stubs get OK declares output as application/json
     # Not yet implemented?
     Failure/Error: expect(tree).to have_key('application/json')
       expected nil to respond to `has_key?`
     # ./spec/integration/openapi3_spec.rb:106:in `block (6 levels) in <top (required)>'

  2) Generated OpenApi Request Body /stubs post OK declares requestBody is required
     # This output is massaged in SwaggerFormatter#stop, and isn't quite ready here to assert
     Failure/Error: expect(tree[:required]).to eq(true)
     
     NoMethodError:
       undefined method `[]' for nil:NilClass
     # ./spec/integration/openapi3_spec.rb:199:in `block (6 levels) in <top (required)>'

Finished in 0.27787 seconds (files took 0.78128 seconds to load)
31 examples, 0 failures, 2 pending

Coverage report generated for RSpec to /Users/bijan/dev/ruby/rswag/test-app/coverage. 66 / 68 LOC (97.06%) covered.
.

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) swagger-ui browsing api-docs
     # Needs work to run on others' machines
     # ./spec/features/swagger_ui_spec.rb:5

  2) Generated OpenApi Media Types /stubs get OK declares output as application/json
     # Not yet implemented?
     Failure/Error: expect(tree).to have_key('application/json')
       expected nil to respond to `has_key?`
     # ./spec/integration/openapi3_spec.rb:106:in `block (6 levels) in <top (required)>'

  3) Generated OpenApi Request Body /stubs post OK declares requestBody is required
     # This output is massaged in SwaggerFormatter#stop, and isn't quite ready here to assert
     Failure/Error: expect(tree[:required]).to eq(true)
     
     NoMethodError:
       undefined method `[]' for nil:NilClass
     # ./spec/integration/openapi3_spec.rb:199:in `block (6 levels) in <top (required)>'

Finished in 1.58 seconds (files took 0.81148 seconds to load)
33 examples, 0 failures, 3 pending

Coverage report generated for RSpec to /Users/bijan/dev/ruby/rswag/test-app/coverage. 66 / 68 LOC (97.06%) covered.

```

### CODE REVIEW

**Comment by Roguelazer** [comment]
Any chance to move this forward? We're currently using a fork with rswag-ui bumped to 5.9.0 because there are so many bugs in 4.1.x

**Comment by gobijan** [comment]
Just bumped my pr to now latest 5.9.0

**Review by romanblanco — CHANGES_REQUESTED** [review]
Changes look good to me :+1: 

@gobijan, please, update the `CHANGELOG.md`

**Comment by gobijan** [comment]
Updated CHANGELOG.md and bumped to latest release 5.9.4

**Review by romanblanco — APPROVED** [review]

**Pull request merged**
